version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: bridge
    hostname: pi4-01-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/London
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE= 0 00 12 * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
#      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=grid1uk@aol.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=graham.dimmock@hotmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.aol.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Watchtower Alert - Container Updates
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=grid1uk@aol.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
    restart: unless-stopped
